### ISSUE TITLE
pybites challenge 01...from/import

### ISSUE THREAD

**Issue by qt3m45su0najc7** [bbelderbos/feedback#1]
Hello Bob,
I am beginning the fundamentals in Python. With challenge 01, I've followed most of the code samples offered and alternate solutions, but amazingly one statement did not get any explanation, "from data import DICTIONARY, LETTER_SCORES".  I understand import is used to import a module, but the purpose of the entire statement isn't clear.  Is it a means to identify the path to the dictionary?  _Data_ is not a standard module, neither are dictionary (import dictionary).

I'm using anaconda and jupyter for building code and I'm not clear about how to reference the dictionary data file as I didn't see it demonstrated in the solution by referencing a particular path, unless it was implicitly in the same folder as the jupyter workbook and there were specific naming rules that need to be adhered to. ('m on windows, of course.

If you think there is some additional light that could be shed on the solution, just update the solution with some additional verbiage and I'll work through it.  The review is here: [https://pybit.es/codechallenge01_review.html](https://pybit.es/codechallenge01_review.html)

Thanks,
Albert Farewege

**Comment by bbelderbos** [comment]
Hi there, import serves for modules and variables inside modules:

```
$ pwd
/Users/bobbelderbos/code/challenges/01
$ python
>>> import os
>>> os.path.isfile('data.py')
True
>>> import data
>>> data
<module 'data' from '/Users/bobbelderbos/code/challenges/01/data.py'>
>>> dir(data)
['DICTIONARY', 'LETTER_SCORES', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'scrabble_scores']
>>> data.LETTER_SCORES
{'E': 1, 'A': 1, 'O': 1, 'I': 1, 'N': 1, 'R': 1, 'T': 1, 'L': 1, 'S': 1, 'U': 1, 'D': 2, 'G': 2, 'B': 3, 'C': 3, 'M': 3, 'P': 3, 'F': 4, 'H': 4, 'V': 4, 'W': 4, 'Y': 4, 'K': 5, 'J': 8, 'X': 8, 'Q': 10, 'Z': 10}
# or import specifically giving the imported constant an alias:
>>> from data import LETTER_SCORES as scores
>>> scores
{'E': 1, 'A': 1, 'O': 1, 'I': 1, 'N': 1, 'R': 1, 'T': 1, 'L': 1, 'S': 1, 'U': 1, 'D': 2, 'G': 2, 'B': 3, 'C': 3, 'M': 3, 'P': 3, 'F': 4, 'H': 4, 'V': 4, 'W': 4, 'Y': 4, 'K': 5, 'J': 8, 'X': 8, 'Q': 10, 'Z': 10}
>>>
```

I hope this clarifies it a bit more, if not maybe we should write something up on PyBites :)

**Comment by qt3m45su0najc7** [comment]
Thank you. I'll play with your examples to digest it.
IMHO, it's worthy of elaboration on pybites.  Feeding many fish is better than feeding one.

**Comment by bbelderbos** [comment]
Yeah let's work on an article, I think modules and the import system can cause confusing, specially for newer Pythonistas. Thanks for raising it.
